### ISSUE TITLE
Download issue with ASCII characters on Synology

### ISSUE THREAD

**Issue by JamesRagnarok** [TDCPF/hath#3] opened 2024-09-30 19:18 UTC
I deployed this docker image on Synology NAS (DSM 7.2.2, Container Manager 20.10.23-1437). While downloading files with ASCII characters in file names, directories with garbled characters were created, and the files failed to download. 

```
2024-09-30T19:11:08Z [WARN] GalleryDownloader: Encountered error while downloading download/[MANA] ???? 1~7+??+ WIP (??) [???] [???] [???] [3024901-780x]/13_13.jpg
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: download/[MANA] ???? 1~7+??+ WIP (??) [???] [???] [???] [3024901-780x]/13_13.jpg
	at sun.nio.fs.UnixPath.encode(Unknown Source)
	at sun.nio.fs.UnixPath.<init>(Unknown Source)
	at sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
	at java.io.File.toPath(Unknown Source)
	at hath.base.GalleryDownloader$GalleryFile.download(GalleryDownloader.java:393)
	at hath.base.GalleryDownloader.run(GalleryDownloader.java:91)
	at java.lang.Thread.run(Unknown Source)
```
With the following env arg set in Container Manager, ASCII characters successfully showed in error messages, but directories with garbled characters still created and failed to download files.
`JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8`

```
2024-09-30T19:01:05Z [WARN] GalleryDownloader: Encountered error while downloading download/[MANA] エウルア 1~7+無字+ WIP (原神) [高解析] [日本語] [無修正] [3024901-780x]/01_1.jpg
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: download/[MANA] エウルア 1~7+無字+ WIP (原神) [高解析] [日本語] [無修正] [3024901-780x]/01_1.jpg
	at sun.nio.fs.UnixPath.encode(Unknown Source)
	at sun.nio.fs.UnixPath.<init>(Unknown Source)
	at sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
	at java.io.File.toPath(Unknown Source)
	at hath.base.GalleryDownloader$GalleryFile.download(GalleryDownloader.java:393)
	at hath.base.GalleryDownloader.run(GalleryDownloader.java:91)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by RoyLi-Pvt** [comment] 2024-12-02 16:51
Same here

**Comment by RoyLi-Pvt** [comment] 2024-12-02 17:01
``` shell
  --env LANG=en_US.UTF-8 \
  --env JAVA_TOOL_OPTIONS="-Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8" \
```

work for me

**Comment by NotExist** [comment] 2024-12-25 09:21
First of all, thanks for all your study and report here. I'm very sorry that I didn't realize such big issue right after changing the base image.
And I just found my hathdl content broken for half year already, oops.
Now it should be fixed in https://github.com/TDCPF/hath/commit/de7cd5ba94b51932d8980d974f9f3aba5b4cb7c9 .

**Closed as completed** 2024-12-25 09:21 UTC

**Comment by NotExist** [comment] 2024-12-25 09:28
BTW, by my understanding, the root cause of the issue is "Downloading with folders/galleries which contains **non-ANSI/ASCII** characters" in their name, instead of "**ASCII** characters in file names".
If the gallery name you're working with contains ASCII characters only, you should run into no problem at all.
